# Practical - 6

### AIM
#### Perform basic operations on matrices (like addition, subtraction, multiplication) and display specific rows or columns of the matrix.

### CODE & OUTPUT

In [1]:
# matrix multiplication using numpy
import numpy as np
mat1 = ([1, 2, 3], [4, 5, 6], [7, 8, 9])
mat2 = ([9, 8, 7], [6, 5, 4], [3, 2, 1])
result = np.dot(mat1, mat2)
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [2]:
# matrix addition using numpy
addition = np.add(mat1, mat2)
print(addition)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [3]:
# matrix subtraction using numpy
sub = np.subtract(mat1, mat2)
print(sub)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
